config/routes.rb
Rails.application.routes.draw do
  
  root 'tweets#index'
  
  
  get 'feed' => 'epicenter#feed'
  
  get 'user_profile' => 'epicenter#show_user'

  post 'now_following' => 'epicenter#now_following'
  
  post 'unfollow' => 'epicenter#unfollow'
  
  get 'about' => 'welcome#about'
  
  get 'contact' => 'welcome#contact'

  get 'js_practice' => 'epicenter#js_practice'

  resources :tweets
  resources :account_activations, only: [:edit]
  devise_for :users

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  validates :message, presence: true
  validates :message, length: {maximum: 140, 
    too_long: "A tweet is only 140 max. Everybody knows that!"}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable   
  has_many :tweets

  validates :username, presence: true, uniqueness: true
  serialize :following, Array
  serialize :follower, Array

  before_create :create_activation
  attr_accessor :remember_token, :activation_token
end

private

def create_activation
  self.activation_token = User.new_token
  self.activation = User.digest(activation_token)
end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, 
      :name, :username, :bio, :location, :following) }

    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, 
      :current_password, :name, :username, :bio, :location, :following) }

  end


end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController
  def feed
    @following_tweets = []    
    @tweets = Tweet.all     
    @tweets.each do |tweet|
      if current_user.following.include?(tweet.user.id)      
      @following_tweets.push(tweet)
    end          
end

    @follower_count = 0 
    @users = User.all 
    @users.each do |user|
      if user.following.include?(current_user.id)
        @follow_count += 0
    end
  end
end

  def show_user
    @user = User.find(params[:id])
  end

  def now_following
    @user = User.find(params[:follow_id])
    # this code will show the <p> You are now following: <%= @user.username %></p>
    current_user.following.push(params[:follow_id].to_i)
    current_user.save #we do this to save
    redirect_to feed_path(id: @user.id)
  end

  def unfollow
    @user = User.find(params[:unfollow_id])
    current_user.following.delete(params[:unfollow_id].to_i)
    current_user.save
    redirect_to feed_path(id: @user.id)
  end

  def js_practice
    
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/epicenter/feed.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <h1>Your Twitter Feed</h1>  
<p>Hello, <%= current_user.name %>!</p>
    <p>Here is what your friends are saying:</p>
  </div>
</div>

<div class="row">
  <div class="current-user-profile-box col-md-4 panel panel-default">
    <div class="panel-body">
      <div class="row">
        <h3><%= current_user.name %> </h3>
        <p><%= current_user.username %> </p>
      </div>
      <div class="row">
        <div class="col-md-4">
          <span class="small-text">TWEETS</span><br />
          <%= current_user.tweets.count %>
        </div>
        <div class="col-md-4">
          <span class="small-text">FOLLOWING</span><br />
          <%= current_user.following.length %>
        </div>
        <div class="col-md-4">
          <span class="small-text">FOLLOWERS</span><br />
          <%= @follower_count %>
        </div> 
      </div>
    </div>      
  </div>
  <div class="following-feed-box col-md-7 col-md-offset-1 panel panel-default">
    <div class="panel-body">
       <% @following_tweets.each do |tweet| %>
       <p>
         <strong><%= link_to tweet.user.username, user_profile_path(id: tweet.user.id) %>:</strong><br />
         <%= tweet.message %>
       </p>
       <% end %>   
    </div>  
  </div>  
</div>  

app/views/epicenter/js_practice.html.erb
<script>

function showMe() {

    document.getElementById("peek").innerHTML = "Here I am!";
  }
function addItUp() {
  var sum = 2 + 2; 
  return sum;
}

function answerMe() {
  document.getElementById("HTML").innerHTML = "Hypertext Markup Language";
}

function display() {
  document.getElementById("CSS").innerHTML = "Cascading Stylesheets";
}

$(document).ready(function(){
  $("#celebrate").click(function(){
    $(".hiphop").html("HOORAY");
  });
});

$(document).ready(funciton(){
  $("#changestyles").click(funciton(){
    $("#nowred").css({"color":"red"});
    $("#nowblue").addClass("blue");
    $("#wasgray").removeClass("gray");
  });
});

</script>


<p id = "peek"> Where is that guy? </p>
<button type="button" onclick="showMe()"> Look! </button>

<p id = "2 + 2"> What is 2 + 2 equal to ? </p>
<button type="button" onclick="addItUp()"> Answer </button>

<p id = "HTML"> What does HTML stand for? </p>
<button type="button" onclick="answerMe()"> Answer </button>

<p id = "CSS"> What does CSS stand for? </p>
<button type="button" onclick="display()"> Answer </button>

<p class="hiphop">Yay? </p>
<p class="hiphip">Super-duper?</p>
<button id="celebrate">Get excited!</button>

<p id="nowred">This text will be red.</p>
<p id="nowblue">This text will be blue.</p>
<p id="wasgray" class="gray">This text was gray.</p>
<button id="changestyles">Change the Styles</button>


app/views/epicenter/now_following.html.erb
<h1>Epicenter</h1>

<h2>Congratulations</h2>
<p>You're now following: <%= @user.username %></p>

app/views/epicenter/show_user.html.erb
<h1><%= @user.username %></h1>
<h3><%= @user.location %></h3>
<h3>Bio:</h3>
<p><%= @user.bio %></p>

<div class="row">
    <% @user.tweets.each do |tweet| %>
    <div class="col-mid-12">
      <div class="panel panel-default">
        <div class="panel-body">
          <p><%= tweet.message %></p>
        </div>
      </div>
    </div>
    <% end %>
</div>

<% if current_user.id != @user.id %>
      <%= form_tag('/unfollow') do %>
        <div class="cant-see-me">
          <%= text_field_tag :unfollow_id, @user.id %>
        </div> <br />
      <%= submit_tag "Unfollow", class: "btn btn-alert" %>
      <% end %>
    </div>
  <% else %>
    <div>
      <%= form_tag('/now_following') do %>
        <div class="cant-see-me">
          <%= text_field_tag :follow_id, @user.id %>
        </div> <br />
      <%= submit_tag "Follow", class: "btn btn-primary" %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/epicenter/unfollow.html.erb
<h1>Unfollow</h1>
<p>Now, you're not following <%= @user.username %> *sad face* </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rsoon TwitterHouse</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to "Rsoon TwitterHouse", root_path, class: "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to "All Tweets", tweets_path %></li>
          <li><%= link_to "Feed", feed_path %></li>

        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign Up",  new_user_registration_path %></li>
          <li><%= link_to "Forgot Password",  new_user_password_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :message %><br>
    <%= f.text_field :message, class: "form-control" %>
  </div>
  <div class="form-group cant-see-me">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit "Tweet", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tweets</h1>

<table class="table">
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to "Rsoontwitterhouse", root_path, class: "navbar-brand"%>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "All Tweets", tweets_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Forgot Password", new_user_password_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.message %></td>
        <td><%= link_to tweet.user.username, user_profile_path(id: tweet.user.id) %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @tweet.message %>
</p>

<p>
  <strong>User:</strong>
  <%= link_to @tweet.user.username, user_profile_path(id: @tweet.user.id) %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

app/views/welcome/about.html.erb
<h1>About RsoonTwitterHouse</h1>
<p>Rsoon Twitter House is another Twitterbase for those who are amatuers.</p>
<h2>Just kidding</h2>
<h3>This is a practice tutorial for classwork</h3>

app/views/welcome/contact.html.erb
<h1>Contact Us</h1>
<p>You can reach out to us by phone, email, or twitterhouse.</p>

app/views/welcome/index.html.erb
<h1>Welcome</h1>
<p>You've arrived to </p>
<p>Rsoon's</p>
  <p>TwitterHouse!!!</p>